version: '3.8'

services:
  web:
    build: .
    command: npm start
    ports:
      - "80:80"
      - "443:443"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DATABASE}
    networks:
      - my_network

networks:
  my_network:
